In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_moons

In [4]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['species'] = encoder.fit_transform(df['species'])

In [7]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:-1], df.iloc[:,-1],test_size =0.2, random_state=1)

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [19]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [20]:
clf1.fit(x_train, y_train)
clf2.fit(x_train, y_train)

DecisionTreeClassifier()

In [21]:
y_pred1 = clf1.predict(x_test)
y_pred2 = clf2.predict(x_test)

In [15]:
from sklearn.metrics import accuracy_score, confusion_matrix
print("Accuracy of Logistic Regression", accuracy_score(y_test, y_pred1))
print("Accuracy of Decision Tree", accuracy_score(y_test, y_pred2))

Accuracy of Logistic Regression 0.9666666666666667
Accuracy of Decision Tree 0.9666666666666667

In [17]:
print("Logistic Regression Confusion Matrix \n")
pd.DataFrame(confusion_matrix(y_test, y_pred1), columns=list(range(0,3)))

Logistic Regression Confusion Matrix

    0   1  2
0  11   0  0
1   0  12  1
2   0   0  6

In [18]:
print("Decision Tree Matrix \n")
pd.DataFrame(confusion_matrix(y_test, y_pred2), columns=list(range(0,3)))

Decision Tree Matrix

    0   1  2
0  11   0  0
1   0  12  1
2   0   0  6

In [22]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2
result.sample(10)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
131             2                               2                         2
78              1                               1                         1
40              0                               0                         0
35              0                               0                         0
31              0                               0                         0
44              0                               0                         0
102             2                               2                         2
73              1                               1                         1
146             2                               2                         2
75              1                               1                         1

In [23]:
from sklearn.metrics import precision_score , recall_score
precision_score(y_test, y_pred1, average=None)

array([1.        , 1.        , 0.85714286])

In [24]:
recall_score(y_test, y_pred1, average=None)

array([1.        , 0.92307692, 1.        ])